import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { DataProvider, DataContext } from '../contexts/DataContext';
import BarChart from '../components/BarChart/BarChart';
import { useContext } from 'react';

export default function Context() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Context</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Hello Context</h1>
        <section>
          <h1>Hello popular celebrities</h1>
          <p>
            According to the movies database the current most popular people
            are:
          </p>
          <DataProvider>
            {/* <List /> */}
            <BarChart
              dataset={''}
              chartWidth={600}
              chartHeight={400}
              string={'name'}
              numerical={'rating'}
            />
          </DataProvider>
        </section>
      </main>
    </div>
  );
}
