import Head from 'next/head'
import { Footer } from '../components/footer/Footer'
import styles from '../styles/Home.module.css'

export default function Context() {

  return (
    <div className={styles.container}>
    <Head>
      <title>Frontend Applications</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <h1>Hello Context</h1>
    </main>
    <Footer />
    </div>
  )
}