import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/Navbar'
import { Footer } from '../components/footer/Footer'
import { DataProvider } from '../contexts/DataContext'
import List from '../components/list/List'
import BarChart from '../components/BarChart/BarChart'
import DataContext from '../contexts/DataContext'
import { useContext } from 'react'


const arr = [{slug: '/one', title: 'one'},{slug: '/two', title: 'two'}]

export default function Home() {
  const data = useContext(DataContext)
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar 
        title={'Some'}
        pages={arr}
        handle={'bommezijn'}
      />
      <main>
        <DataProvider>
            <section>
              {/* <List /> */}
              {DataContext && <BarChart dWidth={600} dHeight={400}/>}
            </section>
          </DataProvider>
      </main>
      <Footer />
    </div>
  )
}


