import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Footer } from '../components/footer/Footer'
import { DataProvider } from '../contexts/DataContext'
import List from '../components/list/List'
import BarChart from '../components/BarChart/BarChart'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h1>Hello popular celebrities</h1>
          <p>According to the movies database the current most popular people are:</p>
          <DataProvider>
              {/* <List /> */}
            <BarChart chartWidth={600} chartHeight={400}/>
          </DataProvider>
        </section>
      </main>
      <Footer />
    </div>
  )
}


